[build]
    command = "npm run build"
    publish = "public"

[[redirects]]
    from = "/contentful"
    to = "https://app.contentful.com/spaces/d3ttfid6hh7h/entries"

[[redirects]]
    from = "/shopify"
    to = "https://iron-jimmy-sleeves.myshopify.com/admin"
